//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Footer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Footer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Shared._Footer", typeof(_Footer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2018 Invesafe P.F.C. S.A..
        /// </summary>
        public static string copyBrand {
            get {
                return ResourceManager.GetString("copyBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2018 INVESAFE | Invesafe SA - Registered in the Registry of Legal Entities in Esc. Nº 345, 02/20/2018, Folio 482, Reg. 134 CBA.,.
        /// </summary>
        public static string footerP1 {
            get {
                return ResourceManager.GetString("footerP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our platform is in the analysis phase before the CNV. File No. 2350/2016..
        /// </summary>
        public static string footerP2 {
            get {
                return ResourceManager.GetString("footerP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invesafe is a participatory financing platform that offers the possibility of investing in Projects of natural persons or societies previously studied and analyzed..
        /// </summary>
        public static string footerP3 {
            get {
                return ResourceManager.GetString("footerP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invesafe does not provide financial advice and nothing on this website should be construed as such. The information that appears on these pages is for general information purposes and does not constitute specific advice. Collective financing projects published on the website are not subject to authorization or supervision by the CMNV or the Central Bank of the Argentine Republic or any other regulator, national or foreign. The information provided by the designer or entrepreneur has not been reviewed or app [rest of string was truncated]&quot;;.
        /// </summary>
        public static string footerP4 {
            get {
                return ResourceManager.GetString("footerP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likewise, the instruments to be issued in the event of a successful subscription are automatically excluded from the requirements and requirements of the Public Offering regime that, in the framework of Law No. 26,831, is authorized by the National Securities Commission. The PFC does not hold the status of a bank or financial entity, and it is not attached to any investment guarantee fund..
        /// </summary>
        public static string footerP5 {
            get {
                return ResourceManager.GetString("footerP5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a risk of total or partial loss of the invested capital, risk of not obtaining the expected monetary return and risk of illiquidity to recover your investment. In the case of social participation, there is also the risk of dilution, of not receiving dividends, of not being able to influence the management of the company and of the restrictions on free transferability inherent in its legal regime..
        /// </summary>
        public static string footerP6 {
            get {
                return ResourceManager.GetString("footerP6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The capital invested is not guaranteed by the investment guarantee fund or the deposit guarantee fund..
        /// </summary>
        public static string footerP7 {
            get {
                return ResourceManager.GetString("footerP7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invesafe.
        /// </summary>
        public static string lblBrand {
            get {
                return ResourceManager.GetString("lblBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us?.
        /// </summary>
        public static string lnkAboutUs {
            get {
                return ResourceManager.GetString("lnkAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic information.
        /// </summary>
        public static string lnkBasicInformation {
            get {
                return ResourceManager.GetString("lnkBasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string lnkFAQ {
            get {
                return ResourceManager.GetString("lnkFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does it work.
        /// </summary>
        public static string lnkHowWork {
            get {
                return ResourceManager.GetString("lnkHowWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invesafe Reports.
        /// </summary>
        public static string lnkInvesafeReports {
            get {
                return ResourceManager.GetString("lnkInvesafeReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunities.
        /// </summary>
        public static string lnkOpportunities {
            get {
                return ResourceManager.GetString("lnkOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string lnkPrivacyPolicy {
            get {
                return ResourceManager.GetString("lnkPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string lnkSupport {
            get {
                return ResourceManager.GetString("lnkSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        public static string lnkUseConditions {
            get {
                return ResourceManager.GetString("lnkUseConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@invesafe.com.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Invesafe.
        /// </summary>
        public static string titAboutInvesafe {
            get {
                return ResourceManager.GetString("titAboutInvesafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string titInfo {
            get {
                return ResourceManager.GetString("titInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participate in Invesafe.
        /// </summary>
        public static string titJoinInvesafe {
            get {
                return ResourceManager.GetString("titJoinInvesafe", resourceCulture);
            }
        }
    }
}
