//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Header {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Header() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Shared._Header", typeof(_Header).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Factor.
        /// </summary>
        public static string lbl2Factor {
            get {
                return ResourceManager.GetString("lbl2Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actived.
        /// </summary>
        public static string lblActived {
            get {
                return ResourceManager.GetString("lblActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string lblAuthentication {
            get {
                return ResourceManager.GetString("lblAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain.
        /// </summary>
        public static string lblGain {
            get {
                return ResourceManager.GetString("lblGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Main Site.
        /// </summary>
        public static string lblGoToSite {
            get {
                return ResourceManager.GetString("lblGoToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do I have a problem?.
        /// </summary>
        public static string lblHaveAProblem {
            get {
                return ResourceManager.GetString("lblHaveAProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invest.
        /// </summary>
        public static string lblInvest {
            get {
                return ResourceManager.GetString("lblInvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invested.
        /// </summary>
        public static string lblInvested {
            get {
                return ResourceManager.GetString("lblInvested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invest in some project.
        /// </summary>
        public static string lblInvestSomeProject {
            get {
                return ResourceManager.GetString("lblInvestSomeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Movements.
        /// </summary>
        public static string lblMovAccount {
            get {
                return ResourceManager.GetString("lblMovAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string lblSite {
            get {
                return ResourceManager.GetString("lblSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string lblSms {
            get {
                return ResourceManager.GetString("lblSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string lblWithdraw {
            get {
                return ResourceManager.GetString("lblWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw Profit.
        /// </summary>
        public static string lblWithdrawProfit {
            get {
                return ResourceManager.GetString("lblWithdrawProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Account.
        /// </summary>
        public static string mnuActiveAccount {
            get {
                return ResourceManager.GetString("mnuActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aditional Data.
        /// </summary>
        public static string mnuAditionalData {
            get {
                return ResourceManager.GetString("mnuAditionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Method.
        /// </summary>
        public static string mnuAuthenticationMethod {
            get {
                return ResourceManager.GetString("mnuAuthenticationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Accounts.
        /// </summary>
        public static string mnuBankAccounts {
            get {
                return ResourceManager.GetString("mnuBankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Bank Activity.
        /// </summary>
        public static string mnuBankActivity {
            get {
                return ResourceManager.GetString("mnuBankActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Information.
        /// </summary>
        public static string mnuBankData {
            get {
                return ResourceManager.GetString("mnuBankData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string mnuBasicInformation {
            get {
                return ResourceManager.GetString("mnuBasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string mnuChangePassword {
            get {
                return ResourceManager.GetString("mnuChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Session.
        /// </summary>
        public static string mnuCloseSession {
            get {
                return ResourceManager.GetString("mnuCloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string mnuDashboard {
            get {
                return ResourceManager.GetString("mnuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Funds.
        /// </summary>
        public static string mnuEntryFunds {
            get {
                return ResourceManager.GetString("mnuEntryFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string mnuExit {
            get {
                return ResourceManager.GetString("mnuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string mnuInfo {
            get {
                return ResourceManager.GetString("mnuInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invesafe Reports.
        /// </summary>
        public static string mnuInvesafeReports {
            get {
                return ResourceManager.GetString("mnuInvesafeReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Investments.
        /// </summary>
        public static string mnuInvestments {
            get {
                return ResourceManager.GetString("mnuInvestments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string mnuMyAccount {
            get {
                return ResourceManager.GetString("mnuMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string mnuNotifications {
            get {
                return ResourceManager.GetString("mnuNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunities.
        /// </summary>
        public static string mnuOpportunities {
            get {
                return ResourceManager.GetString("mnuOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrimonial Situation.
        /// </summary>
        public static string mnuPatrimonialSituation {
            get {
                return ResourceManager.GetString("mnuPatrimonialSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Data.
        /// </summary>
        public static string mnuPersonalData {
            get {
                return ResourceManager.GetString("mnuPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Documentation.
        /// </summary>
        public static string mnuPersonalDocuments {
            get {
                return ResourceManager.GetString("mnuPersonalDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string mnuPrivacyPolicy {
            get {
                return ResourceManager.GetString("mnuPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retire Funds.
        /// </summary>
        public static string mnuRetireFunds {
            get {
                return ResourceManager.GetString("mnuRetireFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string mnuSupport {
            get {
                return ResourceManager.GetString("mnuSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Account.
        /// </summary>
        public static string mnuTypeAccount {
            get {
                return ResourceManager.GetString("mnuTypeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Conditions.
        /// </summary>
        public static string mnuUseConditions {
            get {
                return ResourceManager.GetString("mnuUseConditions", resourceCulture);
            }
        }
    }
}
