//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Messages.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code has expired..
        /// </summary>
        public static string errorCodeExpired {
            get {
                return ResourceManager.GetString("errorCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code entered has expired or does not correspond to the one shown according to its authentication method. Please try again..
        /// </summary>
        public static string errorCodeInvalid {
            get {
                return ResourceManager.GetString("errorCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code entered does not correspond to the one sent by SMS. Please try again..
        /// </summary>
        public static string errorCodeInvalidSMS {
            get {
                return ResourceManager.GetString("errorCodeInvalidSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to save the transaction. Please try again later or contact the technical department..
        /// </summary>
        public static string errorProcedure {
            get {
                return ResourceManager.GetString("errorProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transfer cannot be loaded, since there is still one in the system that was not validated..
        /// </summary>
        public static string errorRetireNotApproved {
            get {
                return ResourceManager.GetString("errorRetireNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image corresponding to the back of the document could not be uploaded correctly. Please try again..
        /// </summary>
        public static string errorUploadDocumentBack {
            get {
                return ResourceManager.GetString("errorUploadDocumentBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image corresponding to the front of the document could not be uploaded correctly. Please try again..
        /// </summary>
        public static string errorUploadDocumentFront {
            get {
                return ResourceManager.GetString("errorUploadDocumentFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not upload attached files correctly. Please try again..
        /// </summary>
        public static string errorUploadDocuments {
            get {
                return ResourceManager.GetString("errorUploadDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try to upload the image again.
        /// </summary>
        public static string errorUploadFileNotFound {
            get {
                return ResourceManager.GetString("errorUploadFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too large, maximum size supported: {0}.
        /// </summary>
        public static string errorUploadSizeLong {
            get {
                return ResourceManager.GetString("errorUploadSizeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a registered user with that email. The procedure cannot be carried out. Please try another account..
        /// </summary>
        public static string errorUserExist {
            get {
                return ResourceManager.GetString("errorUserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a registered user with that email. Authentication will proceed..
        /// </summary>
        public static string infoUserExist {
            get {
                return ResourceManager.GetString("infoUserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string loginError1 {
            get {
                return ResourceManager.GetString("loginError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is locked to continue being used. Please contact support..
        /// </summary>
        public static string loginError10 {
            get {
                return ResourceManager.GetString("loginError10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not registered.
        /// </summary>
        public static string loginError2 {
            get {
                return ResourceManager.GetString("loginError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already registered.
        /// </summary>
        public static string loginError3 {
            get {
                return ResourceManager.GetString("loginError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I expire the time to change the password.
        /// </summary>
        public static string loginError4 {
            get {
                return ResourceManager.GetString("loginError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to change your password.
        /// </summary>
        public static string loginError7 {
            get {
                return ResourceManager.GetString("loginError7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I expire the time to confirm the email account. Please confirm your email account or contact support..
        /// </summary>
        public static string loginError9 {
            get {
                return ResourceManager.GetString("loginError9", resourceCulture);
            }
        }
    }
}
