//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Info {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Info() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Messages.Info", typeof(Info).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the code sent to you by email to continue..
        /// </summary>
        public static string codeFail {
            get {
                return ResourceManager.GetString("codeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string errorFieldRequired {
            get {
                return ResourceManager.GetString("errorFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format is incorrect..
        /// </summary>
        public static string errorIncorrectFormat {
            get {
                return ResourceManager.GetString("errorIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} characters minimum and {1} maximum.
        /// </summary>
        public static string errorNlength {
            get {
                return ResourceManager.GetString("errorNlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} characters maximum.
        /// </summary>
        public static string errorNmaxlength {
            get {
                return ResourceManager.GetString("errorNmaxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} characters minimum.
        /// </summary>
        public static string errorNminlength {
            get {
                return ResourceManager.GetString("errorNminlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords entered do not match.
        /// </summary>
        public static string errorPasswordDiferent {
            get {
                return ResourceManager.GetString("errorPasswordDiferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supported format is: {0}.
        /// </summary>
        public static string errorUploadWrongFormat {
            get {
                return ResourceManager.GetString("errorUploadWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to continue.
        /// </summary>
        public static string loginConfirm {
            get {
                return ResourceManager.GetString("loginConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You still have pending tasks to start investing in projects announced in Invesafe. By clicking on each task you can go to the page that will allow you to complete the information..
        /// </summary>
        public static string statePending {
            get {
                return ResourceManager.GetString("statePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data and documents provided are being validated to comply with the established legality. As soon as they are verified, you will be able to access the necessary data to be able to operate with your Invesafe account.
        /// </summary>
        public static string statePendingIdentity {
            get {
                return ResourceManager.GetString("statePendingIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your statement is in review status as some documents were rejected..
        /// </summary>
        public static string stateRejected {
            get {
                return ResourceManager.GetString("stateRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your documents are being verified. The process can take between 1 and 3 days. Any questions, please go to &lt;a href=&quot;mailto:{0}&quot;&gt; {0} &lt;/a&gt;..
        /// </summary>
        public static string stateValidating {
            get {
                return ResourceManager.GetString("stateValidating", resourceCulture);
            }
        }
    }
}
