//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Warning {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Warning() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Messages.Warning", typeof(Warning).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the conditions to continue..
        /// </summary>
        public static string aceptAgree {
            get {
                return ResourceManager.GetString("aceptAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum to invest in this project is ${0}, since this amount is what is missing to reach the target amount to be collected..
        /// </summary>
        public static string amountFail {
            get {
                return ResourceManager.GetString("amountFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account number already exists within your records. You cannot continue saving it..
        /// </summary>
        public static string errorAccountExist {
            get {
                return ResourceManager.GetString("errorAccountExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected account is not valid..
        /// </summary>
        public static string errorAccountInvalid {
            get {
                return ResourceManager.GetString("errorAccountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount entered of ${0} exceeds the maximum available to withdraw from ${1}. Please decrease the value to be withdrawn..
        /// </summary>
        public static string errorAmountMaxRetry {
            get {
                return ResourceManager.GetString("errorAmountMaxRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount entered to invest is greater than the current balance of your account. Please decrease the value to invest..
        /// </summary>
        public static string errorAmountToBig {
            get {
                return ResourceManager.GetString("errorAmountToBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount entered exceeds the maximum allowed for a bank transfer. Please decrease the value to invest..
        /// </summary>
        public static string errorAmountTransfer {
            get {
                return ResourceManager.GetString("errorAmountTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload at least one file to continue..
        /// </summary>
        public static string filesIncomplete {
            get {
                return ResourceManager.GetString("filesIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, complete all the information correctly to continue.
        /// </summary>
        public static string formIncomplete {
            get {
                return ResourceManager.GetString("formIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot continue until you enter an amount to invest..
        /// </summary>
        public static string investZero {
            get {
                return ResourceManager.GetString("investZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password does not match.
        /// </summary>
        public static string loginError5 {
            get {
                return ResourceManager.GetString("loginError5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password cannot be the same as the current one.
        /// </summary>
        public static string loginError6 {
            get {
                return ResourceManager.GetString("loginError6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook account not associated, please register your account.
        /// </summary>
        public static string loginError8 {
            get {
                return ResourceManager.GetString("loginError8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a payment method.
        /// </summary>
        public static string selectPayment {
            get {
                return ResourceManager.GetString("selectPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered code is incorrect.
        /// </summary>
        public static string wrongCodeTwoFactor {
            get {
                return ResourceManager.GetString("wrongCodeTwoFactor", resourceCulture);
            }
        }
    }
}
