//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthenticationMethod {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthenticationMethod() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Dashboard.AuthenticationMethod", typeof(AuthenticationMethod).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Double-Factor Authentication.
        /// </summary>
        public static string btn2Factor {
            get {
                return ResourceManager.GetString("btn2Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string btnActive {
            get {
                return ResourceManager.GetString("btnActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string btnVerify {
            get {
                return ResourceManager.GetString("btnVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string inpPhoneNbr {
            get {
                return ResourceManager.GetString("inpPhoneNbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Authenticator.
        /// </summary>
        public static string lblAuthenticationGoogle {
            get {
                return ResourceManager.GetString("lblAuthenticationGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Authenticator.
        /// </summary>
        public static string lblAuthenticationSMS {
            get {
                return ResourceManager.GetString("lblAuthenticationSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Area.
        /// </summary>
        public static string lblCodePhone {
            get {
                return ResourceManager.GetString("lblCodePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        public static string lnkClick {
            get {
                return ResourceManager.GetString("lnkClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Authenticator is a secure and reliable authentication method..
        /// </summary>
        public static string msgInfo1 {
            get {
                return ResourceManager.GetString("msgInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, if you want to use the SMS method, do.
        /// </summary>
        public static string msgInfo2 {
            get {
                return ResourceManager.GetString("msgInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new phone number must be verified by entering the SMS code that will be sent to you. Remember that if you change this number, it will be updated in your &lt;a href=&quot;#&quot; ng-click=&quot;clickSlideAjax(&apos;personaldata&apos;)&quot;&gt;Personal Data&lt;/a&gt;..
        /// </summary>
        public static string msgWarning {
            get {
                return ResourceManager.GetString("msgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Method.
        /// </summary>
        public static string subTitle {
            get {
                return ResourceManager.GetString("subTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your phone number or a two-factor authentication method. One of these is required to sign contracts..
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable double factor authentication.
        /// </summary>
        public static string titEnable2Factor {
            get {
                return ResourceManager.GetString("titEnable2Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SMS authentication.
        /// </summary>
        public static string titEnableSMS {
            get {
                return ResourceManager.GetString("titEnableSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Validated.
        /// </summary>
        public static string titPhone {
            get {
                return ResourceManager.GetString("titPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then enter the code below to verify and enable two-factor authentication:.
        /// </summary>
        public static string txt2Factor {
            get {
                return ResourceManager.GetString("txt2Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan this QR code with your Google authentication application:.
        /// </summary>
        public static string txtQR {
            get {
                return ResourceManager.GetString("txtQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the code sent by SMS to the telephone number in the following text box.
        /// </summary>
        public static string txtSMSPhone {
            get {
                return ResourceManager.GetString("txtSMSPhone", resourceCulture);
            }
        }
    }
}
