//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BankAccounts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BankAccounts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Dashboard.BankAccounts", typeof(BankAccounts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string btnRemove {
            get {
                return ResourceManager.GetString("btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Account.
        /// </summary>
        public static string lblAccountNbr {
            get {
                return ResourceManager.GetString("lblAccountNbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string lblBank {
            get {
                return ResourceManager.GetString("lblBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBU.
        /// </summary>
        public static string lblCBU {
            get {
                return ResourceManager.GetString("lblCBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string lblDocument {
            get {
                return ResourceManager.GetString("lblDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder.
        /// </summary>
        public static string lblOwner {
            get {
                return ResourceManager.GetString("lblOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Documentation.
        /// </summary>
        public static string lnkGoToDocumentation {
            get {
                return ResourceManager.GetString("lnkGoToDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visualize.
        /// </summary>
        public static string lnkView {
            get {
                return ResourceManager.GetString("lnkView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a new account, you will have to upload a receipt that shows that it is in your name.
        /// </summary>
        public static string msgAlert {
            get {
                return ResourceManager.GetString("msgAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document received and waiting to be validated.
        /// </summary>
        public static string status1 {
            get {
                return ResourceManager.GetString("status1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account validated.
        /// </summary>
        public static string status2 {
            get {
                return ResourceManager.GetString("status2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account rejected due to erroneous documentation.
        /// </summary>
        public static string status3 {
            get {
                return ResourceManager.GetString("status3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Accounts.
        /// </summary>
        public static string subTitle {
            get {
                return ResourceManager.GetString("subTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to start investing in real estate published in Invsafe, the first step is to complete the necessary documentation to validate your identity as an investor. &lt;br /&gt; At this time we see that you have to attach some essential documents to continue with the process..
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be able to withdraw money from your Invesafe account you have to associate a bank account that is in your name (in the case of a company, in the name of the company). You can register up to &lt;b&gt;4 different bank accounts&lt;/b&gt; that you can change at any time..
        /// </summary>
        public static string text2 {
            get {
                return ResourceManager.GetString("text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account status.
        /// </summary>
        public static string titAccountStatus {
            get {
                return ResourceManager.GetString("titAccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account information.
        /// </summary>
        public static string titDataAccount {
            get {
                return ResourceManager.GetString("titDataAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Data.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account voucher.
        /// </summary>
        public static string titTicketAccount {
            get {
                return ResourceManager.GetString("titTicketAccount", resourceCulture);
            }
        }
    }
}
