//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntryFunds {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntryFunds() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Dashboard.EntryFunds", typeof(EntryFunds).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string btnSelect {
            get {
                return ResourceManager.GetString("btnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string lblAccountNbr {
            get {
                return ResourceManager.GetString("lblAccountNbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string lblBankName {
            get {
                return ResourceManager.GetString("lblBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBU.
        /// </summary>
        public static string lblCBU {
            get {
                return ResourceManager.GetString("lblCBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer concept.
        /// </summary>
        public static string lblConcept {
            get {
                return ResourceManager.GetString("lblConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Payer.
        /// </summary>
        public static string lblOwner {
            get {
                return ResourceManager.GetString("lblOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string lblProject {
            get {
                return ResourceManager.GetString("lblProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addressee.
        /// </summary>
        public static string lblReceiver {
            get {
                return ResourceManager.GetString("lblReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cash income can be made at the bank.
        /// </summary>
        public static string lblStep3 {
            get {
                return ResourceManager.GetString("lblStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very important.
        /// </summary>
        public static string lblVeryImportant {
            get {
                return ResourceManager.GetString("lblVeryImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Funds.
        /// </summary>
        public static string subTitle {
            get {
                return ResourceManager.GetString("subTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No commission.
        /// </summary>
        public static string subTitleTransfer {
            get {
                return ResourceManager.GetString("subTitleTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We remind you what are the details of the trust account to make the transfer from your own account and thus confirm your investment..
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Information.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wire transfer.
        /// </summary>
        public static string titTransfer {
            get {
                return ResourceManager.GetString("titTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transfer payer must match the holder of this Invesafe account. If you make the transfer from an account where there is &lt;strong&gt;more than one owner&lt;/strong&gt; add &quot;{0}&quot; to the concept of the transfer..
        /// </summary>
        public static string txtOwner {
            get {
                return ResourceManager.GetString("txtOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your bank account from homebanking or from a self-service ATM..
        /// </summary>
        public static string txtStep1 {
            get {
                return ResourceManager.GetString("txtStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up the recipient account with the data below..
        /// </summary>
        public static string txtStep2 {
            get {
                return ResourceManager.GetString("txtStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the transfer..
        /// </summary>
        public static string txtStep3 {
            get {
                return ResourceManager.GetString("txtStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait 3 (three) business days for the funds to be credited to the trust account..
        /// </summary>
        public static string txtStep4 {
            get {
                return ResourceManager.GetString("txtStep4", resourceCulture);
            }
        }
    }
}
