//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FAQ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FAQ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Dashboard.FAQ", typeof(FAQ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invesafe is a collective investment platform for real estate projects, or real estate crowdfunding, that allows investors and real estate developers to obtain a better financing alternative to those currently in the market. Investors can invest from small amounts and jointly with other investors in the same real estate project.
        /// </summary>
        public static string answer1 {
            get {
                return ResourceManager.GetString("answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of course, we make available to investors the documentation of the asset as well as the address so they can visit and corroborate physically..
        /// </summary>
        public static string answer10 {
            get {
                return ResourceManager.GetString("answer10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your investment will be backed by an ordinary trust contract for each project. Each contract stipulates all the information of the project and your investment percentage according to the amount you have allocated..
        /// </summary>
        public static string answer11 {
            get {
                return ResourceManager.GetString("answer11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es un contrato en la cual una persona (inversor) le transmite un capital a otra (promotor), en donde este promotor la ejerce en beneficio al inversor, en un determinado tiempo o hasta que se cumpla una condición *.&lt;/p&gt;&lt;p&gt;&lt;span style=&quot;font-size: 11px; line-height: 11px;&quot;&gt;(*) The trust is a contract in which a party (Trustee -&amp;gt; Investor), transmits or agrees to transfer money (Investment) to another person (Trustee), who undertakes to exercise it for the benefit of another so-called beneficiary (Investor / [rest of string was truncated]&quot;;.
        /// </summary>
        public static string answer12 {
            get {
                return ResourceManager.GetString("answer12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our focus is mainly on residential and commercial properties. These properties in which you can invest, will always be at the price of construction cost (in a well), for renovations or as an opportunity at a price substantially lower than that offered in the market. Thus being a unique opportunity to obtain a good return on investment..
        /// </summary>
        public static string answer2 {
            get {
                return ResourceManager.GetString("answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investing in Real Estate is not easy, it requires a lot of time, knowledge and great capital. That&apos;s why we created this platform! So you can invest here in your city, with the capital you have and through real estate experts..
        /// </summary>
        public static string answer3 {
            get {
                return ResourceManager.GetString("answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In our Invesafe platform, you will have an account as an investor where you can control and manage your investments from anywhere and at any time. Periodically, our auditors will upload all the information on the progress of works, evolution and information on each project so you can be calm and see day by day how your investment grows..
        /// </summary>
        public static string answer4 {
            get {
                return ResourceManager.GetString("answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We perform a due diligence to know how the promoter has worked, requesting references and reviewing the legal and financial documentation of the company..
        /// </summary>
        public static string answer5 {
            get {
                return ResourceManager.GetString("answer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do this through a team of specialists, who rigorously analyze and audit the real estate opportunities offered by the different real estate developers. We select only those that have an attractive value in relation to the acquisition cost, construction and / or construction cost, general characteristics, location of the property and the potential future value of the property for sale and rent, according to market trends. This minimizes any investment risk..
        /// </summary>
        public static string answer6 {
            get {
                return ResourceManager.GetString("answer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, it&apos;s easy! Once you have your investment account, you must choose which projects you would like to invest and then just wait to receive your earnings. We will take care of everything..
        /// </summary>
        public static string answer7 {
            get {
                return ResourceManager.GetString("answer7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, creating your Invesafe account is free and you won&apos;t have any fixed maintenance expenses either..
        /// </summary>
        public static string answer8 {
            get {
                return ResourceManager.GetString("answer8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are directly associated with the success of each project and we only charge a 10% commission on the profit you will receive from your investment. The higher profitability we achieve, the more you and we win.
        /// </summary>
        public static string answer9 {
            get {
                return ResourceManager.GetString("answer9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does Invesafe work?.
        /// </summary>
        public static string question1 {
            get {
                return ResourceManager.GetString("question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can you see the property?.
        /// </summary>
        public static string question10 {
            get {
                return ResourceManager.GetString("question10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What legal documentation supports my investment?.
        /// </summary>
        public static string question11 {
            get {
                return ResourceManager.GetString("question11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is a trust?.
        /// </summary>
        public static string question12 {
            get {
                return ResourceManager.GetString("question12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What kind of projects are offered?.
        /// </summary>
        public static string question2 {
            get {
                return ResourceManager.GetString("question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why invest in Invesafe?.
        /// </summary>
        public static string question3 {
            get {
                return ResourceManager.GetString("question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What control do I have of my investment?.
        /// </summary>
        public static string question4 {
            get {
                return ResourceManager.GetString("question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is the process of acceptance of real estate developers?.
        /// </summary>
        public static string question5 {
            get {
                return ResourceManager.GetString("question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does Invesafe select the projects to be financed?.
        /// </summary>
        public static string question6 {
            get {
                return ResourceManager.GetString("question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it easy to participate?.
        /// </summary>
        public static string question7 {
            get {
                return ResourceManager.GetString("question7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it have any cost?.
        /// </summary>
        public static string question8 {
            get {
                return ResourceManager.GetString("question8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does Invesafe earn?.
        /// </summary>
        public static string question9 {
            get {
                return ResourceManager.GetString("question9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string subTitle {
            get {
                return ResourceManager.GetString("subTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Invesafe.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
