//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HowWork {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HowWork() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Dashboard.HowWork", typeof(HowWork).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does it work?.
        /// </summary>
        public static string subTitle {
            get {
                return ResourceManager.GetString("subTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free registration.
        /// </summary>
        public static string tit1 {
            get {
                return ResourceManager.GetString("tit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your project.
        /// </summary>
        public static string tit2 {
            get {
                return ResourceManager.GetString("tit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decide the amount to invest.
        /// </summary>
        public static string tit3 {
            get {
                return ResourceManager.GetString("tit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor your investment.
        /// </summary>
        public static string tit4 {
            get {
                return ResourceManager.GetString("tit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize your earnings.
        /// </summary>
        public static string tit5 {
            get {
                return ResourceManager.GetString("tit5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Invesafe.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access all the opportunities available to invest with a safe and easy-to-use dashboard..
        /// </summary>
        public static string txt1 {
            get {
                return ResourceManager.GetString("txt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Know the different &lt;a href=&quot;#&quot; ng-click=&quot;clickSlideAjax(&apos;opportunities&apos;)&quot;&gt;available projects&lt;/a&gt;, analyze the options and choose the one that best suits your investment plan..
        /// </summary>
        public static string txt2 {
            get {
                return ResourceManager.GetString("txt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decide the amount of your investment. Consider diversifying your capital into more than one project..
        /// </summary>
        public static string txt3 {
            get {
                return ResourceManager.GetString("txt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the evolution of &lt;a href=&quot;#&quot; ng-click=&quot;clickSlideAjax(&apos;myinvestments&apos;)&quot;&gt;your investments&lt;/a&gt; from our platform..
        /// </summary>
        public static string txt4 {
            get {
                return ResourceManager.GetString("txt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinvest or collect your earnings at the end of the project..
        /// </summary>
        public static string txt5 {
            get {
                return ResourceManager.GetString("txt5", resourceCulture);
            }
        }
    }
}
