//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Opportunities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Opportunities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Dashboard.Opportunities", typeof(Opportunities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invest.
        /// </summary>
        public static string btnInvest {
            get {
                return ResourceManager.GetString("btnInvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Project.
        /// </summary>
        public static string btnViewProject {
            get {
                return ResourceManager.GetString("btnViewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;TOTAL PROFITABILITY&lt;/strong&gt;: It is the estimated total return on investment in the duration of the opportunity..
        /// </summary>
        public static string info1 {
            get {
                return ResourceManager.GetString("info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;TERM&lt;/strong&gt;: It is the estimated duration of the opportunity..
        /// </summary>
        public static string info2 {
            get {
                return ResourceManager.GetString("info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Historical IRR&lt;/strong&gt;: Average rate of projects of this type completed so far. It is used to evaluate, from a financial perspective, the profitability of a project or set of projects and compare with other types of investment in the market; It is always expressed as a percentage. INVESAFE calculates the IRR of the estimates of the set of income throughout the life of the different projects in each of its typologies..
        /// </summary>
        public static string info3 {
            get {
                return ResourceManager.GetString("info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string lblDay {
            get {
                return ResourceManager.GetString("lblDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string lblDay_S {
            get {
                return ResourceManager.GetString("lblDay_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical IRR.
        /// </summary>
        public static string lblHistoricTIR {
            get {
                return ResourceManager.GetString("lblHistoricTIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to investor.
        /// </summary>
        public static string lblInvestor {
            get {
                return ResourceManager.GetString("lblInvestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string lblInvestor_S {
            get {
                return ResourceManager.GetString("lblInvestor_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profitability.
        /// </summary>
        public static string lblProfit {
            get {
                return ResourceManager.GetString("lblProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        public static string lblTerm {
            get {
                return ResourceManager.GetString("lblTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Profitability.
        /// </summary>
        public static string lblTotalProf {
            get {
                return ResourceManager.GetString("lblTotalProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunities.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE INFORMATION.
        /// </summary>
        public static string titMoreInformation {
            get {
                return ResourceManager.GetString("titMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project has stipulated {{project.goalDays}} days to complete the collection from the start date of the project..
        /// </summary>
        public static string txtInfo {
            get {
                return ResourceManager.GetString("txtInfo", resourceCulture);
            }
        }
    }
}
