//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PatrimonialSituation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatrimonialSituation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Dashboard.PatrimonialSituation", typeof(PatrimonialSituation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money available to invest.
        /// </summary>
        public static string lblAvailableMoney {
            get {
                return ResourceManager.GetString("lblAvailableMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average capital invested per project.
        /// </summary>
        public static string lblAvgCapitalInvested {
            get {
                return ResourceManager.GetString("lblAvgCapitalInvested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits.
        /// </summary>
        public static string lblBenefits {
            get {
                return ResourceManager.GetString("lblBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invested capital.
        /// </summary>
        public static string lblCapitalInvested {
            get {
                return ResourceManager.GetString("lblCapitalInvested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Benefits.
        /// </summary>
        public static string lblExtraBenefits {
            get {
                return ResourceManager.GetString("lblExtraBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraordinary expenses.
        /// </summary>
        public static string lblExtraExpense {
            get {
                return ResourceManager.GetString("lblExtraExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invesafe Commissions.
        /// </summary>
        public static string lblInvesafeFee {
            get {
                return ResourceManager.GetString("lblInvesafeFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses.
        /// </summary>
        public static string lblLosses {
            get {
                return ResourceManager.GetString("lblLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyect number.
        /// </summary>
        public static string lblNbrProject {
            get {
                return ResourceManager.GetString("lblNbrProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net profit.
        /// </summary>
        public static string lblNetBenefit {
            get {
                return ResourceManager.GetString("lblNetBenefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits for purchase of shares.
        /// </summary>
        public static string lblPurchaseBenefits {
            get {
                return ResourceManager.GetString("lblPurchaseBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real estate sale benefits.
        /// </summary>
        public static string lblSaleBenefits {
            get {
                return ResourceManager.GetString("lblSaleBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal benefits.
        /// </summary>
        public static string lblSubtotalBenefits {
            get {
                return ResourceManager.GetString("lblSubtotalBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal expenses.
        /// </summary>
        public static string lblSubtotalExpense {
            get {
                return ResourceManager.GetString("lblSubtotalExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Benefits.
        /// </summary>
        public static string lblTaxBenefits {
            get {
                return ResourceManager.GetString("lblTaxBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total equity value.
        /// </summary>
        public static string lblTotalPatrimonial {
            get {
                return ResourceManager.GetString("lblTotalPatrimonial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see your balance, you must first complete the main data of your profile. (Profile data in the &lt;a ng-click=&quot;clickSlideAjax(&apos;personaldata&apos;)&quot;&gt;&quot;Personal Data&quot;&lt;/a&gt; section)..
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrimonial Situation.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string titResults {
            get {
                return ResourceManager.GetString("titResults", resourceCulture);
            }
        }
    }
}
