//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersonalData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonalData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Dashboard.PersonalData", typeof(PersonalData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication method is by SMS and the number is already validated. For that reason it cannot be modified, change the &lt;a href=&quot;#&quot; ng-click=&quot;clickSlideAjax(&apos;authenticationmethod&apos;)&quot;&gt;authentication method&lt;/a&gt; to enable editing..
        /// </summary>
        public static string infoPhone {
            get {
                return ResourceManager.GetString("infoPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They are all national, provincial, municipal or Autonomous City of Buenos Aires public officials, foreign public officials and family members of the Politically Exposed Person, who serve or have served up to two years prior to the date on which it was carried out the operative Why do we ask for it? Because it is a norm requested by the authorities in Argentina..
        /// </summary>
        public static string infoPolitician {
            get {
                return ResourceManager.GetString("infoPolitician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string inpAddress {
            get {
                return ResourceManager.GetString("inpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code.
        /// </summary>
        public static string inpAreaCode {
            get {
                return ResourceManager.GetString("inpAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string inpBornDate {
            get {
                return ResourceManager.GetString("inpBornDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string inpCity {
            get {
                return ResourceManager.GetString("inpCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string inpCountry {
            get {
                return ResourceManager.GetString("inpCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUIT number.
        /// </summary>
        public static string inpCUIT {
            get {
                return ResourceManager.GetString("inpCUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string inpEmail {
            get {
                return ResourceManager.GetString("inpEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First and Second Name.
        /// </summary>
        public static string inpFullName {
            get {
                return ResourceManager.GetString("inpFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string inpLastName {
            get {
                return ResourceManager.GetString("inpLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string inpNationality {
            get {
                return ResourceManager.GetString("inpNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string inpPhone {
            get {
                return ResourceManager.GetString("inpPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you politically exposed?.
        /// </summary>
        public static string inpPolitician {
            get {
                return ResourceManager.GetString("inpPolitician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP.
        /// </summary>
        public static string inpZip {
            get {
                return ResourceManager.GetString("inpZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your address as it appears on your utility bills..
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your full CUIT without spaces or special characters..
        /// </summary>
        public static string lblCUIT {
            get {
                return ResourceManager.GetString("lblCUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Investor Data.
        /// </summary>
        public static string subTitle {
            get {
                return ResourceManager.GetString("subTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These data correspond to the owner of the Invesafe account..
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Residence.
        /// </summary>
        public static string titAddress {
            get {
                return ResourceManager.GetString("titAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification data.
        /// </summary>
        public static string titIdentificationData {
            get {
                return ResourceManager.GetString("titIdentificationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string titNationality {
            get {
                return ResourceManager.GetString("titNationality", resourceCulture);
            }
        }
    }
}
