//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Project {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Detail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Detail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Project.Detail", typeof(Detail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more details see the &lt;a href=&quot;#&quot; ng-click=&quot;openDocumentation()&quot;&gt;project documentation&lt;/a&gt;..
        /// </summary>
        public static string infoProject {
            get {
                return ResourceManager.GetString("infoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan amount requested by the developer..
        /// </summary>
        public static string infoRef1 {
            get {
                return ResourceManager.GetString("infoRef1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest to be distributed monthly among investors..
        /// </summary>
        public static string infoRef2 {
            get {
                return ResourceManager.GetString("infoRef2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase of the asset (${{project.purchasePrice}}) including all expenses associated with the operation: real estate acquisition price, brokerage fees, legal costs, sales and fees charged by Invesafe to the developer..
        /// </summary>
        public static string infoRef3 {
            get {
                return ResourceManager.GetString("infoRef3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate legal expenses, VAT deductible and mattress for exploitation. Also in case of reform: construction / reform costs, taxes, procedures and legal costs of the reform and furniture..
        /// </summary>
        public static string infoRef4 {
            get {
                return ResourceManager.GetString("infoRef4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated profit after the sale of the Property..
        /// </summary>
        public static string infoRef5 {
            get {
                return ResourceManager.GetString("infoRef5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated amount on the performance obtained at the end of the project..
        /// </summary>
        public static string lblEstimatedAmount {
            get {
                return ResourceManager.GetString("lblEstimatedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Financing.
        /// </summary>
        public static string lblFinancialClose {
            get {
                return ResourceManager.GetString("lblFinancialClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial documents.
        /// </summary>
        public static string lblFinancialDocuments {
            get {
                return ResourceManager.GetString("lblFinancialDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Financing.
        /// </summary>
        public static string lblFinancialStart {
            get {
                return ResourceManager.GetString("lblFinancialStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fractions.
        /// </summary>
        public static string lblFractions {
            get {
                return ResourceManager.GetString("lblFractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financing objective.
        /// </summary>
        public static string lblGoalFinancial {
            get {
                return ResourceManager.GetString("lblGoalFinancial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Value Fraction.
        /// </summary>
        public static string lblInitialValue {
            get {
                return ResourceManager.GetString("lblInitialValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment.
        /// </summary>
        public static string lblInvest {
            get {
                return ResourceManager.GetString("lblInvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invest now.
        /// </summary>
        public static string lblInvestNow {
            get {
                return ResourceManager.GetString("lblInvestNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to investor.
        /// </summary>
        public static string lblInvestor {
            get {
                return ResourceManager.GetString("lblInvestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string lblInvestor_S {
            get {
                return ResourceManager.GetString("lblInvestor_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to invest.
        /// </summary>
        public static string lblIWantInvest {
            get {
                return ResourceManager.GetString("lblIWantInvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could receive.
        /// </summary>
        public static string lblIwillGet {
            get {
                return ResourceManager.GetString("lblIwillGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal documents.
        /// </summary>
        public static string lblLegalDocuments {
            get {
                return ResourceManager.GetString("lblLegalDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction Market Value.
        /// </summary>
        public static string lblMarketValue {
            get {
                return ResourceManager.GetString("lblMarketValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monetary investment.
        /// </summary>
        public static string lblMonetaryInvest {
            get {
                return ResourceManager.GetString("lblMonetaryInvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string lblMonth_S {
            get {
                return ResourceManager.GetString("lblMonth_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERATION ANALYSIS.
        /// </summary>
        public static string lblOperationAnalysis {
            get {
                return ResourceManager.GetString("lblOperationAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERATION DATA.
        /// </summary>
        public static string lblOperationData {
            get {
                return ResourceManager.GetString("lblOperationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Benefit.
        /// </summary>
        public static string lblOperationProfit {
            get {
                return ResourceManager.GetString("lblOperationProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents of the opportunity.
        /// </summary>
        public static string lblOportunityDocuments {
            get {
                return ResourceManager.GetString("lblOportunityDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string lblPurchase {
            get {
                return ResourceManager.GetString("lblPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALE ANALYSIS.
        /// </summary>
        public static string lblSaleAnalysis {
            get {
                return ResourceManager.GetString("lblSaleAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit from the sale.
        /// </summary>
        public static string lblSaleProfit {
            get {
                return ResourceManager.GetString("lblSaleProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERM.
        /// </summary>
        public static string lblTerm {
            get {
                return ResourceManager.GetString("lblTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL PROFITABILITY.
        /// </summary>
        public static string lblTotalProfit {
            get {
                return ResourceManager.GetString("lblTotalProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Opportunities.
        /// </summary>
        public static string lnkBack {
            get {
                return ResourceManager.GetString("lnkBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no documents uploaded for this project..
        /// </summary>
        public static string noData {
            get {
                return ResourceManager.GetString("noData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string tab1 {
            get {
                return ResourceManager.GetString("tab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial information.
        /// </summary>
        public static string tab2 {
            get {
                return ResourceManager.GetString("tab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string tab3 {
            get {
                return ResourceManager.GetString("tab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunities.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
