//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Project {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntryFunds {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntryFunds() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Project.EntryFunds", typeof(EntryFunds).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transfer payer must match the holder of this Invesafe account. If you transfer from an account where there is &lt;strong&gt;more than one owner&lt;/strong&gt; add &quot;&lt;strong&gt;{{bankAccount.label}}-{{bankAccount.referenceCode}}-TIT&lt;/strong&gt;&quot; to the concept of the transference..
        /// </summary>
        public static string infoOwner {
            get {
                return ResourceManager.GetString("infoOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cash income can be made at the bank.
        /// </summary>
        public static string infoStep3 {
            get {
                return ResourceManager.GetString("infoStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addressee.
        /// </summary>
        public static string lblAddressee {
            get {
                return ResourceManager.GetString("lblAddressee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the bank.
        /// </summary>
        public static string lblBankName {
            get {
                return ResourceManager.GetString("lblBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBU.
        /// </summary>
        public static string lblCBU {
            get {
                return ResourceManager.GetString("lblCBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer concept.
        /// </summary>
        public static string lblConceptTransfer {
            get {
                return ResourceManager.GetString("lblConceptTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number.
        /// </summary>
        public static string lblNroAccount {
            get {
                return ResourceManager.GetString("lblNroAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Transfer.
        /// </summary>
        public static string lblOwner {
            get {
                return ResourceManager.GetString("lblOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very important.
        /// </summary>
        public static string lblVeryImportant {
            get {
                return ResourceManager.GetString("lblVeryImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the Opportunity.
        /// </summary>
        public static string lnkBack {
            get {
                return ResourceManager.GetString("lnkBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your bank account from homebanking or from a self-service ATM..
        /// </summary>
        public static string step1 {
            get {
                return ResourceManager.GetString("step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up the recipient account with the data below..
        /// </summary>
        public static string step2 {
            get {
                return ResourceManager.GetString("step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the transfer..
        /// </summary>
        public static string step3 {
            get {
                return ResourceManager.GetString("step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait 3 (three) business days for the funds to be credited to the trust account..
        /// </summary>
        public static string step4 {
            get {
                return ResourceManager.GetString("step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Funds.
        /// </summary>
        public static string subTitle {
            get {
                return ResourceManager.GetString("subTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No commission.
        /// </summary>
        public static string subTitleNoCommission {
            get {
                return ResourceManager.GetString("subTitleNoCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enter funds into the trust account by bank transfer from your own account..
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment / Project.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wire transfer.
        /// </summary>
        public static string titTransfer {
            get {
                return ResourceManager.GetString("titTransfer", resourceCulture);
            }
        }
    }
}
