//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Project {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Invest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Invest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Project.Invest", typeof(Invest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Investment.
        /// </summary>
        public static string btnConfirm {
            get {
                return ResourceManager.GetString("btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string btnNext {
            get {
                return ResourceManager.GetString("btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and accept the &lt;a ng-href=&quot;{0}&quot; target=&quot;_blank&quot;&gt;Investor Terms and Conditions&lt;/a&gt; and I declare under oath that my total investment in Projects published in the group of collective financing platforms, within the same calendar year period, do not represent more than 20% of my annual gross income, according to the last fiscal year closed..
        /// </summary>
        public static string chkAgree {
            get {
                return ResourceManager.GetString("chkAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital after investing.
        /// </summary>
        public static string lblAfterInvest {
            get {
                return ResourceManager.GetString("lblAfterInvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital to invest.
        /// </summary>
        public static string lblCapitalToInvest {
            get {
                return ResourceManager.GetString("lblCapitalToInvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current capital in the account.
        /// </summary>
        public static string lblCurrentCapital {
            get {
                return ResourceManager.GetString("lblCurrentCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTIMATED TOTAL PROFITABILITY.
        /// </summary>
        public static string lblEstimatedProfit {
            get {
                return ResourceManager.GetString("lblEstimatedProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string lblMonth_S {
            get {
                return ResourceManager.GetString("lblMonth_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. fractions.
        /// </summary>
        public static string lblNoFractions {
            get {
                return ResourceManager.GetString("lblNoFractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Summary.
        /// </summary>
        public static string lblResumeCapital {
            get {
                return ResourceManager.GetString("lblResumeCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERM.
        /// </summary>
        public static string lblTerm {
            get {
                return ResourceManager.GetString("lblTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Opportunities.
        /// </summary>
        public static string lnkBack {
            get {
                return ResourceManager.GetString("lnkBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invest Now.
        /// </summary>
        public static string subTitle {
            get {
                return ResourceManager.GetString("subTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Confirmation.
        /// </summary>
        public static string titConfirmInvest {
            get {
                return ResourceManager.GetString("titConfirmInvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail of your investment.
        /// </summary>
        public static string titInvestDetail {
            get {
                return ResourceManager.GetString("titInvestDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunities / Project.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before continuing, you must insert in the following text box the code that &lt;span ng-show = &quot;dataHeader.authenticationMethod == 1&quot;&gt;appears in the Google authenticator APP&lt;/span&gt;&lt;span ng-show = &quot;dataHeader.authenticationMethod == 2 &quot;&gt;sent to you by SMS&lt;/span&gt;..
        /// </summary>
        public static string txtConfirmInvest {
            get {
                return ResourceManager.GetString("txtConfirmInvest", resourceCulture);
            }
        }
    }
}
