//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Investment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BuyInvest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuyInvest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Investment.BuyInvest", typeof(BuyInvest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Market Place.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Investment.
        /// </summary>
        public static string btnConfirm {
            get {
                return ResourceManager.GetString("btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and accept the &lt;a ng-href=&quot;{0}&quot; target=&quot;_blank&quot;&gt;Mandate Contract&lt;/a&gt; and the &lt;a ng-href=&quot;{1}&quot; target=&quot;_blank&quot;&gt;Contract Investment&lt;/a&gt; and I confirm that my total investment does not exceed $ 10,000 in projects published in the set of participatory financing platforms.
        /// </summary>
        public static string chkAgree {
            get {
                return ResourceManager.GetString("chkAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital to invest.
        /// </summary>
        public static string lblCapitalToInvest {
            get {
                return ResourceManager.GetString("lblCapitalToInvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction value.
        /// </summary>
        public static string lblFractionValue {
            get {
                return ResourceManager.GetString("lblFractionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string lblMonth_S {
            get {
                return ResourceManager.GetString("lblMonth_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. fractions.
        /// </summary>
        public static string lblNroFractions {
            get {
                return ResourceManager.GetString("lblNroFractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Investment.
        /// </summary>
        public static string subTitle {
            get {
                return ResourceManager.GetString("subTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail of your Investment.
        /// </summary>
        public static string titInvestDetail {
            get {
                return ResourceManager.GetString("titInvestDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Place / Project.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERM.
        /// </summary>
        public static string titTerm {
            get {
                return ResourceManager.GetString("titTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL PROFITABILITY.
        /// </summary>
        public static string titTotalProfit {
            get {
                return ResourceManager.GetString("titTotalProfit", resourceCulture);
            }
        }
    }
}
