//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Investment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Sale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Investment.Sale", typeof(Sale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Market Place.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sales Order.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Sales Order.
        /// </summary>
        public static string btnPublish {
            get {
                return ResourceManager.GetString("btnPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete order.
        /// </summary>
        public static string btnRemove {
            get {
                return ResourceManager.GetString("btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and accept the &lt;a ng-href=&quot;{0}&quot; target=&quot;_blank&quot;&gt;Sale Contract&lt;/a&gt;..
        /// </summary>
        public static string chkAgree {
            get {
                return ResourceManager.GetString("chkAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated capital.
        /// </summary>
        public static string lblCapitalEstimated {
            get {
                return ResourceManager.GetString("lblCapitalEstimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Cost.
        /// </summary>
        public static string lblCostOrder {
            get {
                return ResourceManager.GetString("lblCostOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace fractions.
        /// </summary>
        public static string lblFractionMP {
            get {
                return ResourceManager.GetString("lblFractionMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction value.
        /// </summary>
        public static string lblFractionValue {
            get {
                return ResourceManager.GetString("lblFractionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. fractions.
        /// </summary>
        public static string lblNroFractions {
            get {
                return ResourceManager.GetString("lblNroFractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Investment.
        /// </summary>
        public static string subTitle {
            get {
                return ResourceManager.GetString("subTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractions to sell.
        /// </summary>
        public static string titFractionSale {
            get {
                return ResourceManager.GetString("titFractionSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Detail.
        /// </summary>
        public static string titInvestDetail {
            get {
                return ResourceManager.GetString("titInvestDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Investments / Project.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove order.
        /// </summary>
        public static string titRemove {
            get {
                return ResourceManager.GetString("titRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As an alternative, you can also delete the following sales order so that it does not appear in the marketplace and continue with your investment in the project..
        /// </summary>
        public static string txtInfo {
            get {
                return ResourceManager.GetString("txtInfo", resourceCulture);
            }
        }
    }
}
