//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Bank {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddAccount {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddAccount() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Bank.AddAccount", typeof(AddAccount).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Cuenta Bancaria.
        /// </summary>
        public static string inpAccountNbr {
            get {
                return ResourceManager.GetString("inpAccountNbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Banco.
        /// </summary>
        public static string inpBankName {
            get {
                return ResourceManager.GetString("inpBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código CBU.
        /// </summary>
        public static string inpCBU {
            get {
                return ResourceManager.GetString("inpCBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titular.
        /// </summary>
        public static string inpOwner {
            get {
                return ResourceManager.GetString("inpOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type.
        /// </summary>
        public static string inpTypeAccount {
            get {
                return ResourceManager.GetString("inpTypeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código cuenta bancaria sin espacios ni guiones.
        /// </summary>
        public static string lblAccountNbr {
            get {
                return ResourceManager.GetString("lblAccountNbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjunta un documento bancario, en soporte PDF o similar, donde conste el número de cuenta y tu titularidad. Si tienes algún problema al subir esta documentación puedes enviárnosla a.
        /// </summary>
        public static string lblAddDocument {
            get {
                return ResourceManager.GetString("lblAddDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código CBU sin espacios ni guiones.
        /// </summary>
        public static string lblCBU {
            get {
                return ResourceManager.GetString("lblCBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir un documento.
        /// </summary>
        public static string lblUploadFile {
            get {
                return ResourceManager.GetString("lblUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Bank Accounts.
        /// </summary>
        public static string lnkBack {
            get {
                return ResourceManager.GetString("lnkBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bank Account.
        /// </summary>
        public static string subTitle {
            get {
                return ResourceManager.GetString("subTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to &lt;b&gt;withdraw money from your Invesafe Account&lt;/b&gt; you have to associate a bank account that is in your name (in the case of a company in the name of the company). You can register &lt;b&gt;up to 4 different bank accounts&lt;/b&gt; that you can change whenever you want (to do so you will have to re-upload a document that shows that the new account is in your name)..
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Information.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobante.
        /// </summary>
        public static string titTicket {
            get {
                return ResourceManager.GetString("titTicket", resourceCulture);
            }
        }
    }
}
