//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ale_alert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ale_alert()
        {
            this.axc_alexcli = new HashSet<axc_alexcli>();
        }
    
        public long ale_id { get; set; }
        public Nullable<int> agr_id { get; set; }
        public string ale_message_pending { get; set; }
        public string ale_message_validating { get; set; }
        public string ale_message_approved { get; set; }
        public string ale_message_rejected { get; set; }
        public string ale_link { get; set; }
        public int ale_order { get; set; }
        public bool ale_enable { get; set; }
    
        public virtual agr_alertGroup agr_alertGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<axc_alexcli> axc_alexcli { get; set; }
    }
}
