//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class axc_alexcli
    {
        public long axc_id { get; set; }
        public Nullable<long> cli_id { get; set; }
        public Nullable<long> ale_id { get; set; }
        public Nullable<int> axc_state { get; set; }
        public bool axc_visible { get; set; }
    
        public virtual ale_alert ale_alert { get; set; }
        public virtual cli_client cli_client { get; set; }
    }
}
