//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class invesafeEntities : DbContext
    {
        public invesafeEntities()
            : base("name=invesafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cou_country> cou_country { get; set; }
        public virtual DbSet<lan_language> lan_language { get; set; }
        public virtual DbSet<cad_categoryDocuments> cad_categoryDocuments { get; set; }
        public virtual DbSet<spr_statusProject> spr_statusProject { get; set; }
        public virtual DbSet<dbp_documentsByProject> dbp_documentsByProject { get; set; }
        public virtual DbSet<axc_alexcli> axc_alexcli { get; set; }
        public virtual DbSet<agr_alertGroup> agr_alertGroup { get; set; }
        public virtual DbSet<tac_typeAccount> tac_typeAccount { get; set; }
        public virtual DbSet<tpr_typeProject> tpr_typeProject { get; set; }
        public virtual DbSet<ban_bankAccount> ban_bankAccount { get; set; }
        public virtual DbSet<blo_blob> blo_blob { get; set; }
        public virtual DbSet<rep_report> rep_report { get; set; }
        public virtual DbSet<tpa_typePayment> tpa_typePayment { get; set; }
        public virtual DbSet<rfu_retireFund> rfu_retireFund { get; set; }
        public virtual DbSet<ben_benefit> ben_benefit { get; set; }
        public virtual DbSet<exp_expense> exp_expense { get; set; }
        public virtual DbSet<tbe_typeBenefit> tbe_typeBenefit { get; set; }
        public virtual DbSet<tex_typeExpense> tex_typeExpense { get; set; }
        public virtual DbSet<aca_accreditAccount> aca_accreditAccount { get; set; }
        public virtual DbSet<app_appParameters> app_appParameters { get; set; }
        public virtual DbSet<not_notification> not_notification { get; set; }
        public virtual DbSet<nxc_notxcli> nxc_notxcli { get; set; }
        public virtual DbSet<ale_alert> ale_alert { get; set; }
        public virtual DbSet<pba_projectBankAccount> pba_projectBankAccount { get; set; }
        public virtual DbSet<mov_movement> mov_movement { get; set; }
        public virtual DbSet<top_typeOperation> top_typeOperation { get; set; }
        public virtual DbSet<sin_saleInvest> sin_saleInvest { get; set; }
        public virtual DbSet<frv_fractionValue> frv_fractionValue { get; set; }
        public virtual DbSet<pro_project> pro_project { get; set; }
        public virtual DbSet<pxc_proxcli> pxc_proxcli { get; set; }
        public virtual DbSet<his_historyClient> his_historyClient { get; set; }
        public virtual DbSet<cli_client> cli_client { get; set; }
    
        public virtual ObjectResult<SP_GET_DOCUMENTS_Result> SP_GET_DOCUMENTS(Nullable<long> cliId, Nullable<long> proId)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            var proIdParameter = proId.HasValue ?
                new ObjectParameter("proId", proId) :
                new ObjectParameter("proId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_DOCUMENTS_Result>("SP_GET_DOCUMENTS", cliIdParameter, proIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_BANKACCOUNTS_Result> SP_GET_BANKACCOUNTS(Nullable<long> cliId)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_BANKACCOUNTS_Result>("SP_GET_BANKACCOUNTS", cliIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_ADITIONALDATA_Result> SP_GET_ADITIONALDATA(Nullable<long> cliId, string cliEmail)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            var cliEmailParameter = cliEmail != null ?
                new ObjectParameter("cliEmail", cliEmail) :
                new ObjectParameter("cliEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ADITIONALDATA_Result>("SP_GET_ADITIONALDATA", cliIdParameter, cliEmailParameter);
        }
    
        public virtual ObjectResult<SP_GET_REPORTS_Result> SP_GET_REPORTS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_REPORTS_Result>("SP_GET_REPORTS");
        }
    
        public virtual ObjectResult<SP_GET_MOVEMENTS_Result> SP_GET_MOVEMENTS(Nullable<long> cliId, Nullable<int> topId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endData)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            var topIdParameter = topId.HasValue ?
                new ObjectParameter("topId", topId) :
                new ObjectParameter("topId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDataParameter = endData.HasValue ?
                new ObjectParameter("endData", endData) :
                new ObjectParameter("endData", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_MOVEMENTS_Result>("SP_GET_MOVEMENTS", cliIdParameter, topIdParameter, startDateParameter, endDataParameter);
        }
    
        public virtual ObjectResult<SP_GET_PATRIMONIALSITUATION_Result> SP_GET_PATRIMONIALSITUATION(Nullable<long> cliId, Nullable<bool> returnFull)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            var returnFullParameter = returnFull.HasValue ?
                new ObjectParameter("returnFull", returnFull) :
                new ObjectParameter("returnFull", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PATRIMONIALSITUATION_Result>("SP_GET_PATRIMONIALSITUATION", cliIdParameter, returnFullParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_GENERATE_HASH(Nullable<long> cli_id)
        {
            var cli_idParameter = cli_id.HasValue ?
                new ObjectParameter("cli_id", cli_id) :
                new ObjectParameter("cli_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GENERATE_HASH", cli_idParameter);
        }
    
        public virtual ObjectResult<SP_GET_NOTIFICATIONS_Result> SP_GET_NOTIFICATIONS(Nullable<long> cliId)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_NOTIFICATIONS_Result>("SP_GET_NOTIFICATIONS", cliIdParameter);
        }
    
        public virtual ObjectResult<SP_MAIL_WELCOME_Result> SP_MAIL_WELCOME(Nullable<long> cli_id)
        {
            var cli_idParameter = cli_id.HasValue ?
                new ObjectParameter("cli_id", cli_id) :
                new ObjectParameter("cli_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MAIL_WELCOME_Result>("SP_MAIL_WELCOME", cli_idParameter);
        }
    
        public virtual ObjectResult<SP_GET_PROJECTBANKACCOUNT_Result> SP_GET_PROJECTBANKACCOUNT(Nullable<long> proId)
        {
            var proIdParameter = proId.HasValue ?
                new ObjectParameter("proId", proId) :
                new ObjectParameter("proId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PROJECTBANKACCOUNT_Result>("SP_GET_PROJECTBANKACCOUNT", proIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_MYINVEST_Result> SP_GET_MYINVEST(Nullable<long> cliId, Nullable<long> pxcId)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            var pxcIdParameter = pxcId.HasValue ?
                new ObjectParameter("pxcId", pxcId) :
                new ObjectParameter("pxcId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_MYINVEST_Result>("SP_GET_MYINVEST", cliIdParameter, pxcIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_MARKETPLACE_Result> SP_GET_MARKETPLACE(Nullable<long> cliId, Nullable<long> proId, Nullable<int> tprId)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            var proIdParameter = proId.HasValue ?
                new ObjectParameter("proId", proId) :
                new ObjectParameter("proId", typeof(long));
    
            var tprIdParameter = tprId.HasValue ?
                new ObjectParameter("tprId", tprId) :
                new ObjectParameter("tprId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_MARKETPLACE_Result>("SP_GET_MARKETPLACE", cliIdParameter, proIdParameter, tprIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_SALE_INVEST_Result> SP_GET_SALE_INVEST(Nullable<long> cliId, Nullable<long> sinId)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            var sinIdParameter = sinId.HasValue ?
                new ObjectParameter("sinId", sinId) :
                new ObjectParameter("sinId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_SALE_INVEST_Result>("SP_GET_SALE_INVEST", cliIdParameter, sinIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_MYINVESTMENTS_Result> SP_GET_MYINVESTMENTS(Nullable<long> cliId, string search, Nullable<int> tprId)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            var tprIdParameter = tprId.HasValue ?
                new ObjectParameter("tprId", tprId) :
                new ObjectParameter("tprId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_MYINVESTMENTS_Result>("SP_GET_MYINVESTMENTS", cliIdParameter, searchParameter, tprIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_PROJECTS_Result> SP_GET_PROJECTS(Nullable<long> cliId)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PROJECTS_Result>("SP_GET_PROJECTS", cliIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_ALERTS_Result> SP_GET_ALERTS(Nullable<long> cliId)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALERTS_Result>("SP_GET_ALERTS", cliIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_PROJECT_Result> SP_GET_PROJECT(Nullable<long> cliId, Nullable<long> proId)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            var proIdParameter = proId.HasValue ?
                new ObjectParameter("proId", proId) :
                new ObjectParameter("proId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PROJECT_Result>("SP_GET_PROJECT", cliIdParameter, proIdParameter);
        }
    
        public virtual ObjectResult<SP_MAIL_RESETPASS_Result> SP_MAIL_RESETPASS(Nullable<long> cli_id)
        {
            var cli_idParameter = cli_id.HasValue ?
                new ObjectParameter("cli_id", cli_id) :
                new ObjectParameter("cli_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MAIL_RESETPASS_Result>("SP_MAIL_RESETPASS", cli_idParameter);
        }
    
        public virtual ObjectResult<SP_GET_TYPEINVERTER_Result> SP_GET_TYPEINVERTER(Nullable<long> cliId)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_TYPEINVERTER_Result>("SP_GET_TYPEINVERTER", cliIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_BANKACCOUNTS_VALIDATED_Result> SP_GET_BANKACCOUNTS_VALIDATED(Nullable<long> cliId)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_BANKACCOUNTS_VALIDATED_Result>("SP_GET_BANKACCOUNTS_VALIDATED", cliIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_BALANCEACCOUNT_Result> SP_GET_BALANCEACCOUNT(Nullable<long> cliId)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_BALANCEACCOUNT_Result>("SP_GET_BALANCEACCOUNT", cliIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_PERSONALDATA_Result> SP_GET_PERSONALDATA(Nullable<long> cliId, string cliEmail)
        {
            var cliIdParameter = cliId.HasValue ?
                new ObjectParameter("cliId", cliId) :
                new ObjectParameter("cliId", typeof(long));
    
            var cliEmailParameter = cliEmail != null ?
                new ObjectParameter("cliEmail", cliEmail) :
                new ObjectParameter("cliEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PERSONALDATA_Result>("SP_GET_PERSONALDATA", cliIdParameter, cliEmailParameter);
        }
    }
}
