//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ben_benefit
    {
        public long ben_id { get; set; }
        public long cli_id { get; set; }
        public long pro_id { get; set; }
        public int tbe_id { get; set; }
        public Nullable<double> ben_amount { get; set; }
        public System.DateTime ben_dateCreate { get; set; }
        public bool ben_enable { get; set; }
    
        public virtual tbe_typeBenefit tbe_typeBenefit { get; set; }
        public virtual pro_project pro_project { get; set; }
        public virtual cli_client cli_client { get; set; }
    }
}
