//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class blo_blob
    {
        public long blo_id { get; set; }
        public Nullable<System.Guid> blo_guid { get; set; }
        public string blo_filename { get; set; }
        public Nullable<int> blo_container { get; set; }
        public string blo_extension { get; set; }
        public Nullable<int> blo_width { get; set; }
        public Nullable<int> blo_height { get; set; }
        public System.DateTime blo_dateCreate { get; set; }
    }
}
