//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class cli_client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cli_client()
        {
            this.aca_accreditAccount = new HashSet<aca_accreditAccount>();
            this.axc_alexcli = new HashSet<axc_alexcli>();
            this.ban_bankAccount = new HashSet<ban_bankAccount>();
            this.ben_benefit = new HashSet<ben_benefit>();
            this.mov_movement = new HashSet<mov_movement>();
            this.nxc_notxcli = new HashSet<nxc_notxcli>();
            this.pxc_proxcli = new HashSet<pxc_proxcli>();
            this.rfu_retireFund = new HashSet<rfu_retireFund>();
            this.sin_saleInvest = new HashSet<sin_saleInvest>();
        }
    
        public long cli_id { get; set; }
        public string cli_firstname { get; set; }
        public string cli_lastname { get; set; }
        public string cli_email { get; set; }
        public string cli_codePhone { get; set; }
        public string cli_phone { get; set; }
        public Nullable<System.DateTime> cli_bornDate { get; set; }
        public Nullable<long> cou_idNationality { get; set; }
        public Nullable<long> cou_idLive { get; set; }
        public string cli_address { get; set; }
        public string cli_cp { get; set; }
        public string cli_city { get; set; }
        public string cli_dni { get; set; }
        public string cli_cuit { get; set; }
        public string cli_cuil { get; set; }
        public Nullable<long> blo_idFront { get; set; }
        public Nullable<long> blo_idBack { get; set; }
        public string cli_password { get; set; }
        public System.DateTime cli_dateCreate { get; set; }
        public Nullable<System.DateTime> cli_dateModify { get; set; }
        public bool cli_enable { get; set; }
        public bool cli_active { get; set; }
        public bool cli_validate { get; set; }
        public Nullable<int> cli_gender { get; set; }
        public Nullable<long> lan_idContact { get; set; }
        public string cli_profession { get; set; }
        public int cli_civilState { get; set; }
        public int cli_typeInvester { get; set; }
        public string cli_idFacebook { get; set; }
        public string cli_hash { get; set; }
        public Nullable<int> cli_exposedPolitician { get; set; }
        public string cli_codeReference { get; set; }
        public Nullable<double> cli_annualIncome { get; set; }
        public Nullable<double> cli_maxInvest { get; set; }
        public int cli_authenticationMethod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aca_accreditAccount> aca_accreditAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<axc_alexcli> axc_alexcli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ban_bankAccount> ban_bankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ben_benefit> ben_benefit { get; set; }
        public virtual cou_country cou_country { get; set; }
        public virtual cou_country cou_country1 { get; set; }
        public virtual lan_language lan_language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mov_movement> mov_movement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nxc_notxcli> nxc_notxcli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pxc_proxcli> pxc_proxcli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rfu_retireFund> rfu_retireFund { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sin_saleInvest> sin_saleInvest { get; set; }
    }
}
