//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class cou_country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cou_country()
        {
            this.cli_client = new HashSet<cli_client>();
            this.cli_client1 = new HashSet<cli_client>();
        }
    
        public long cou_id { get; set; }
        public string cou_countryCode { get; set; }
        public string cou_countryName { get; set; }
        public string cou_currencyCode { get; set; }
        public string cou_fipsCode { get; set; }
        public string cou_isoNumeric { get; set; }
        public string cou_north { get; set; }
        public string cou_south { get; set; }
        public string cou_east { get; set; }
        public string cou_west { get; set; }
        public string cou_capital { get; set; }
        public string cou_continentName { get; set; }
        public string cou_continent { get; set; }
        public string cou_languages { get; set; }
        public string cou_isoAlpha3 { get; set; }
        public Nullable<int> cou_geonameId { get; set; }
        public bool cou_enable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cli_client> cli_client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cli_client> cli_client1 { get; set; }
    }
}
