//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbp_documentsByProject
    {
        public long dbp_id { get; set; }
        public long pro_id { get; set; }
        public int cad_id { get; set; }
        public string dbp_name { get; set; }
        public string dbp_file { get; set; }
        public bool dbp_enable { get; set; }
    
        public virtual cad_categoryDocuments cad_categoryDocuments { get; set; }
        public virtual pro_project pro_project { get; set; }
    }
}
