//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class exp_expense
    {
        public long exp_id { get; set; }
        public long pro_id { get; set; }
        public int tex_id { get; set; }
        public Nullable<double> exp_amount { get; set; }
        public System.DateTime exp_dateCreate { get; set; }
        public bool exp_enable { get; set; }
    
        public virtual tex_typeExpense tex_typeExpense { get; set; }
        public virtual pro_project pro_project { get; set; }
    }
}
