//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class lan_language
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lan_language()
        {
            this.cli_client = new HashSet<cli_client>();
        }
    
        public long lan_id { get; set; }
        public string lan_description { get; set; }
        public string lan_locale { get; set; }
        public string lan_languageCode { get; set; }
        public string lan_lcid { get; set; }
        public Nullable<int> lan_decimal { get; set; }
        public Nullable<int> lan_codePage { get; set; }
        public bool lan_enable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cli_client> cli_client { get; set; }
    }
}
