//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class mov_movement
    {
        public long mov_id { get; set; }
        public long cli_id { get; set; }
        public int top_id { get; set; }
        public double mov_amount { get; set; }
        public int mov_inputOutput { get; set; }
        public string mov_concept { get; set; }
        public bool mov_validate { get; set; }
        public System.DateTime mov_dateCreate { get; set; }
    
        public virtual top_typeOperation top_typeOperation { get; set; }
        public virtual cli_client cli_client { get; set; }
    }
}
