//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class nxc_notxcli
    {
        public long nxc_id { get; set; }
        public Nullable<long> cli_id { get; set; }
        public Nullable<int> not_id { get; set; }
        public bool nxc_enable { get; set; }
    
        public virtual not_notification not_notification { get; set; }
        public virtual cli_client cli_client { get; set; }
    }
}
