//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class pba_projectBankAccount
    {
        public long pba_id { get; set; }
        public Nullable<long> pro_id { get; set; }
        public string pba_bank { get; set; }
        public string pba_owner { get; set; }
        public string pba_accountNbr { get; set; }
        public string pba_cbu { get; set; }
        public string pba_label { get; set; }
        public System.DateTime pba_dateCreate { get; set; }
        public bool pba_enable { get; set; }
    }
}
