//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class pro_project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pro_project()
        {
            this.ben_benefit = new HashSet<ben_benefit>();
            this.dbp_documentsByProject = new HashSet<dbp_documentsByProject>();
            this.exp_expense = new HashSet<exp_expense>();
            this.frv_fractionValue = new HashSet<frv_fractionValue>();
            this.pxc_proxcli = new HashSet<pxc_proxcli>();
        }
    
        public long pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_subName { get; set; }
        public int tpr_id { get; set; }
        public int spr_id { get; set; }
        public long cou_idNationality { get; set; }
        public string pro_city { get; set; }
        public Nullable<System.DateTime> pro_startFinancing { get; set; }
        public double pro_profitability { get; set; }
        public double pro_historicTIR { get; set; }
        public Nullable<double> pro_purchasePrice { get; set; }
        public Nullable<double> pro_price1 { get; set; }
        public Nullable<double> pro_price2 { get; set; }
        public Nullable<double> pro_price3 { get; set; }
        public Nullable<double> pro_price4 { get; set; }
        public Nullable<double> pro_priceTotal { get; set; }
        public int pro_timeLimit { get; set; }
        public string pro_description { get; set; }
        public double pro_goalAmount { get; set; }
        public double pro_maxAmount { get; set; }
        public double pro_minAmount { get; set; }
        public int pro_goalDays { get; set; }
        public double pro_minInvest { get; set; }
        public double pro_maxInvest { get; set; }
        public bool pro_close { get; set; }
        public Nullable<System.DateTime> pro_dateClose { get; set; }
        public bool pro_finish { get; set; }
        public Nullable<System.DateTime> pro_dateFinish { get; set; }
        public System.DateTime pro_dateCreate { get; set; }
        public bool pro_enable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ben_benefit> ben_benefit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbp_documentsByProject> dbp_documentsByProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exp_expense> exp_expense { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<frv_fractionValue> frv_fractionValue { get; set; }
        public virtual spr_statusProject spr_statusProject { get; set; }
        public virtual tpr_typeProject tpr_typeProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pxc_proxcli> pxc_proxcli { get; set; }
    }
}
