//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class pxc_proxcli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pxc_proxcli()
        {
            this.sin_saleInvest = new HashSet<sin_saleInvest>();
        }
    
        public long pxc_id { get; set; }
        public long pro_id { get; set; }
        public long cli_id { get; set; }
        public long pxc_amount { get; set; }
        public int tpa_id { get; set; }
        public bool pxc_haveGain { get; set; }
        public string pxc_code { get; set; }
        public System.DateTime pxc_dateCreate { get; set; }
        public bool pxc_enable { get; set; }
    
        public virtual pro_project pro_project { get; set; }
        public virtual tpa_typePayment tpa_typePayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sin_saleInvest> sin_saleInvest { get; set; }
        public virtual cli_client cli_client { get; set; }
    }
}
