//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class rep_report
    {
        public long rep_id { get; set; }
        public string rep_title { get; set; }
        public string rep_image { get; set; }
        public string rep_file { get; set; }
        public bool rep_enable { get; set; }
        public System.DateTime rep_dateCreate { get; set; }
    }
}
