//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfu_retireFund
    {
        public long rfu_id { get; set; }
        public long cli_id { get; set; }
        public long ban_id { get; set; }
        public double rfu_ammount { get; set; }
        public string rfu_concept { get; set; }
        public bool rfu_validate { get; set; }
        public System.DateTime rfu_dateCreate { get; set; }
    
        public virtual ban_bankAccount ban_bankAccount { get; set; }
        public virtual cli_client cli_client { get; set; }
    }
}
