//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class sin_saleInvest
    {
        public long sin_id { get; set; }
        public long pxc_id { get; set; }
        public Nullable<long> sin_amount { get; set; }
        public Nullable<double> sin_fraction { get; set; }
        public bool sin_sold { get; set; }
        public Nullable<long> cli_idSold { get; set; }
        public System.DateTime sin_dateCreate { get; set; }
        public bool sin_enable { get; set; }
    
        public virtual pxc_proxcli pxc_proxcli { get; set; }
        public virtual cli_client cli_client { get; set; }
    }
}
