//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SignUp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SignUp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Account.SignUp", typeof(SignUp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string btnSignUp {
            get {
                return ResourceManager.GetString("btnSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblInputEmail {
            get {
                return ResourceManager.GetString("lblInputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lblInputFirstName {
            get {
                return ResourceManager.GetString("lblInputFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string lblInputLastName {
            get {
                return ResourceManager.GetString("lblInputLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblInputPassword {
            get {
                return ResourceManager.GetString("lblInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        public static string lblInputRepeatPassword {
            get {
                return ResourceManager.GetString("lblInputRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register with.
        /// </summary>
        public static string lblSignUpWith {
            get {
                return ResourceManager.GetString("lblSignUpWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I already remembered the account! I want to {0}login&lt;/a&gt;.
        /// </summary>
        public static string lnkLogin {
            get {
                return ResourceManager.GetString("lnkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why register?.
        /// </summary>
        public static string titWhySignUp {
            get {
                return ResourceManager.GetString("titWhySignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will access all the projects.
        /// </summary>
        public static string txtAdvantages1 {
            get {
                return ResourceManager.GetString("txtAdvantages1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can invest in a safe way.
        /// </summary>
        public static string txtAdvantages2 {
            get {
                return ResourceManager.GetString("txtAdvantages2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will control the evolution of your capital.
        /// </summary>
        public static string txtAdvantages3 {
            get {
                return ResourceManager.GetString("txtAdvantages3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the internal marketplace.
        /// </summary>
        public static string txtAdvantages4 {
            get {
                return ResourceManager.GetString("txtAdvantages4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 hour permanent support.
        /// </summary>
        public static string txtAdvantages5 {
            get {
                return ResourceManager.GetString("txtAdvantages5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...and much more!.
        /// </summary>
        public static string txtMuchMore {
            get {
                return ResourceManager.GetString("txtMuchMore", resourceCulture);
            }
        }
    }
}
